name: Verify
version: 1.0.0
author: Popcraft
website: https://popcraft.cn
description: 玩家验证插件 - 提供验证码验证和规则书展示功能

api-version: 1.19.3

main: cn.popcraft.verify.VerifyPlugin

# 权限节点
permissions:
  verify.admin:
    description: 管理员权限
    default: op
  verify.reload:
    description: 重载插件配置权限
    default: op
  verify.bypass:
    description: 跳过验证权限
    default: op

# 命令
commands:
  verify:
    description: 验证相关命令
    permission: verify.admin
    permission-message: §c您没有权限使用此命令！
    usage: /verify <reload|help>
    aliases: [vfy]
    tab-completer: cn.popcraft.verify.commands.VerifyTabCompleter

# 事件监听
depend: []